version: '3.9'

services:
  qrcode:
    container_name: qrcode
    image: bizzycolah/qrcode-generator
    ports:
      - 80:80
    healthcheck:
      test: curl -f http://localhost:80/ || exit 1
    mem_limit: 1g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    restart: on-failure:5